### ISSUE TITLE
ضرورت ارائه نسخه EPUB کتاب

### ISSUE THREAD

**Issue by hamedsbt** [ahhshm/clean-code-farsi#95]
سلام. با توجه به اینکه امروزه مطالعه کتاب با تلفن همراه یا کتابخوان بسیار مرسوم شده است و البته همه جا و در هر شرایطی دسترسی به اینترنت مقدور نیست، بنظر میرسد ارائه نسخه EPUB کتاب ضروری است. باتشکر

**Comment by ahhshm** [comment]
سلام
ادامه این پروژه به من سپرده شده
روی این مورد حتما کار میکنم ولی یکم زمان میبره تا یه سیستم درست و حسابی براش پیدا کنم
فعلا این رو میبندم
ممنون
